/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AccesoLogin extends javax.swing.JFrame {
    
    
    int xMouse, yMouse;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccesoLogin.class.getName());

    /**
     * Creates new form Acceso
     */
    public AccesoLogin() {
        initComponents();
      
    }
    
    
    public javax.swing.JTextField gettxtUsuario() {
    return txtUsuario; 
}

    public javax.swing.JPasswordField gettxtContra() {
    return txtContra; 
}


    public javax.swing.JButton getBtnEntrar() {
    return BtnEntrar; 
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        extBtn = new javax.swing.JPanel();
        extSymbol = new javax.swing.JLabel();
        vuelosFis = new javax.swing.JLabel();
        nombreAereo = new javax.swing.JLabel();
        contraLabel = new javax.swing.JLabel();
        InicionLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtContra = new javax.swing.JPasswordField();
        BtnEntrar = new javax.swing.JButton();
        logoMundo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner.setOpaque(false);
        banner.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bannerMouseDragged(evt);
            }
        });
        banner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bannerMousePressed(evt);
            }
        });

        extBtn.setBackground(new java.awt.Color(255, 255, 255));

        extSymbol.setFont(new java.awt.Font("Open Sauce One Light", 0, 18)); // NOI18N
        extSymbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extSymbol.setText("X");
        extSymbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extSymbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extSymbolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extSymbolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extSymbolMouseExited(evt);
            }
        });

        javax.swing.GroupLayout extBtnLayout = new javax.swing.GroupLayout(extBtn);
        extBtn.setLayout(extBtnLayout);
        extBtnLayout.setHorizontalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(extSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        extBtnLayout.setVerticalGroup(
            extBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(extSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addGap(0, 812, Short.MAX_VALUE)
                .addComponent(extBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        vuelosFis.setFont(new java.awt.Font("Open Sauce One Black", 0, 36)); // NOI18N
        vuelosFis.setText("VuelosFIS");
        jPanel2.add(vuelosFis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 190, 60));

        nombreAereo.setFont(new java.awt.Font("Open Sauce One Light", 0, 18)); // NOI18N
        nombreAereo.setText("AerolíneasFIS");
        jPanel2.add(nombreAereo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, 40));

        contraLabel.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 24)); // NOI18N
        contraLabel.setText("Contraseña");
        jPanel2.add(contraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 140, 50));

        InicionLabel.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 36)); // NOI18N
        InicionLabel.setText("Iniciar Sesión");
        jPanel2.add(InicionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 250, 50));

        usuarioLabel.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 24)); // NOI18N
        usuarioLabel.setText("Usuario");
        jPanel2.add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 100, 50));

        txtUsuario.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 320, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 320, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 320, 20));

        txtContra.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        txtContra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContra.setText("******");
        txtContra.setBorder(null);
        txtContra.setMargin(new java.awt.Insets(2, 10, 5, 10));
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        txtContra.addActionListener(this::txtContraActionPerformed);
        jPanel2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 290, 320, 40));

        BtnEntrar.setBackground(new java.awt.Color(69, 130, 177));
        BtnEntrar.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEntrar.setText("Iniciar");
        BtnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEntrarMouseExited(evt);
            }
        });
        BtnEntrar.addActionListener(this::BtnEntrarActionPerformed);
        jPanel2.add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 140, 40));

        logoMundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoMundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoMundo.png"))); // NOI18N
        logoMundo.setText("jLabel2");
        jPanel2.add(logoMundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 200, 200));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 430, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void bannerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bannerMousePressed

    private void bannerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_bannerMouseDragged

    private void extSymbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extSymbolMouseClicked
      System.exit(0);
    }//GEN-LAST:event_extSymbolMouseClicked

    private void extSymbolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extSymbolMouseEntered
        extBtn.setBackground(Color.red);
        extBtn.setForeground(Color.white);
    }//GEN-LAST:event_extSymbolMouseEntered

    private void extSymbolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extSymbolMouseExited
        extBtn.setBackground(Color.white);
        extBtn.setForeground(Color.black);
    }//GEN-LAST:event_extSymbolMouseExited

    private void BtnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEntrarMouseEntered
        BtnEntrar.setBackground(new Color(83, 155, 212));
    }//GEN-LAST:event_BtnEntrarMouseEntered

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
       if(txtUsuario.getText().equals("Ingrese su nombre de usuario")){
       txtUsuario.setText("");
       txtUsuario.setForeground(Color.black);
       }
       if(String.valueOf(txtContra.getPassword()).isEmpty()) {
       txtContra.setText("******");
       txtContra.setForeground(Color.gray);
    }

    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
       if(String.valueOf(txtContra.getPassword()).equals("******")){
       txtContra.setText("");
       txtContra.setForeground(Color.black);
       }
       if(txtUsuario.getText().isEmpty()){
       txtUsuario.setText("Ingrese su nombre de usuario");
       txtUsuario.setForeground(Color.gray);   
           
       }
      
 
    }//GEN-LAST:event_txtContraMousePressed

    private void BtnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEntrarMouseExited
        BtnEntrar.setBackground(new Color(69,130,177));
    }//GEN-LAST:event_BtnEntrarMouseExited

    private void BtnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEntrarMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos: \nUsuario: " + txtUsuario.getText() + "\nContraseña: " + String.valueOf(txtContra.getPassword()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccesoLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JLabel InicionLabel;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel contraLabel;
    private javax.swing.JPanel extBtn;
    private javax.swing.JLabel extSymbol;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoMundo;
    private javax.swing.JLabel nombreAereo;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JLabel vuelosFis;
    // End of variables declaration//GEN-END:variables
}
