/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.time.LocalDate;
import javax.swing.RowFilter;
import javax.swing.RowFilter.Entry;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Avion;
import modelo.Ruta;
import modelo.Vuelo;
import control.ManejadorArchivos;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author USER
 */
public class Catalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Catalogo.class.getName());

    /**
     * Creates new form Catálogo
     */
    
    public Catalogo() {
        initComponents();
    }
    
    public javax.swing.JTable getTblGestionVuelos() {
        return tblGestionVuelos;
    }

    public javax.swing.JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public javax.swing.JTextField getTxtFiltroPrecio() {
        return txtFiltroPrecio;
    }

    public javax.swing.JComboBox<String> getCbxDestino() {
        return cbxDestino;
    }
    
    public javax.swing.JComboBox<String> getCbxOrigen() {
        return cbxOrigen;
    }
    
    public javax.swing.JComboBox<String> getCbxTipoAvion() {
        return cbxTipoAvion;
    }

    public com.github.lgooddatepicker.components.DatePicker getDatesSalida() {
        return dateSalida;
    }

    public com.github.lgooddatepicker.components.DatePicker getDateRegreso() {
        return dateRegreso;
    }
    
    public com.github.lgooddatepicker.components.TimePicker getTmPickSalida() {
        return tmPickSalida;
    }

    public com.github.lgooddatepicker.components.TimePicker getTmPickLlegada() {
        return tmPickLlegada;
    }

    public javax.swing.JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public javax.swing.JButton getBtnContinuar() {
        return btnContinuar;
    }
    
    public javax.swing.JButton getBtnCargarDatos() {
        return btnCargarDatos;
    }

    public javax.swing.JButton getBtnEliminarVuelo() {
        return btnEliminarVuelo;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionVuelos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblResumen = new javax.swing.JLabel();
        dateSalida = new com.github.lgooddatepicker.components.DatePicker();
        jLabelFechaSalida = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        btnNuevoVuelo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarVuelo = new javax.swing.JButton();
        cbxTipoAvion = new javax.swing.JComboBox<>();
        txtFiltroPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelFechaRetorno = new javax.swing.JLabel();
        dateRegreso = new com.github.lgooddatepicker.components.DatePicker();
        cbxDestino = new javax.swing.JComboBox<>();
        cbxOrigen = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        cbxModo = new javax.swing.JComboBox<>();
        tmPickSalida = new com.github.lgooddatepicker.components.TimePicker();
        tmPickLlegada = new com.github.lgooddatepicker.components.TimePicker();
        JTitulo = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(38, 61, 141));

        tblGestionVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Avión", "Origen", "Destino", "Fecha - Salida", "Hora - Salida", "Hora - Llegada", "Fecha - Retorno", "Precio Base", "Tipo - Equipaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGestionVuelos.setBackground(new java.awt.Color(204, 204, 204));
        tblGestionVuelos.setGridColor(new java.awt.Color(38, 61, 141));
        tblGestionVuelos.setSelectionBackground(new java.awt.Color(69, 130, 177));
        tblGestionVuelos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblGestionVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGestionVuelos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen del Vuelo Seleccionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(69, 130, 177))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        lblResumen.setBackground(new java.awt.Color(255, 255, 255));
        lblResumen.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        dateSalida.setBackground(new java.awt.Color(69, 130, 177));
        dateSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        jLabelFechaSalida.setText("Fecha - Salida");
        jLabelFechaSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelFechaSalida.setForeground(new java.awt.Color(38, 61, 141));

        jLabelDestino.setText("Destino");
        jLabelDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(38, 61, 141));

        jLabelOrigen.setText("Origen");
        jLabelOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(38, 61, 141));

        jLabel5.setText("Código");
        jLabel5.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 61, 141));

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.setBackground(new java.awt.Color(69, 130, 177));
        btnCargarDatos.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        btnNuevoVuelo.setText("Nuevo Vuelo");
        btnNuevoVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnNuevoVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnNuevoVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVueloActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBackground(new java.awt.Color(69, 130, 177));
        btnLimpiar.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminarVuelo.setText("Eliminar Vuelo");
        btnEliminarVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnEliminarVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnEliminarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVueloActionPerformed(evt);
            }
        });

        cbxTipoAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Airbus A319", "Airbus A320neo", "Airbus A321", "Boeing 737-800", "ATR 72-600" }));
        cbxTipoAvion.setBackground(new java.awt.Color(69, 130, 177));
        cbxTipoAvion.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxTipoAvion.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoAvionActionPerformed(evt);
            }
        });

        txtFiltroPrecio.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        txtFiltroPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtFiltroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroPrecioActionPerformed(evt);
            }
        });
        txtFiltroPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroPrecioKeyReleased(evt);
            }
        });

        jLabel1.setText("Presupuesto");
        jLabel1.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 61, 141));

        jLabel4.setText("Avión");
        jLabel4.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 61, 141));

        jLabel2.setText("Modo");
        jLabel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 61, 141));
        jLabel2.setToolTipText("");

        jLabel6.setText("Hora - Salida");
        jLabel6.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 61, 141));

        jLabel7.setText("Hora - Llegada");
        jLabel7.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 61, 141));

        jLabelFechaRetorno.setText("Fecha - Regreso");
        jLabelFechaRetorno.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelFechaRetorno.setForeground(new java.awt.Color(38, 61, 141));

        dateRegreso.setBackground(new java.awt.Color(69, 130, 177));
        dateRegreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateRegreso.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Quito", "Guayaquil", "Cuenca" }));
        cbxDestino.setBackground(new java.awt.Color(69, 130, 177));
        cbxDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxDestino.setForeground(new java.awt.Color(255, 255, 255));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        cbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Quito", "Guayaquil", "Cuenca" }));
        cbxOrigen.setBackground(new java.awt.Color(69, 130, 177));
        cbxOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxOrigen.setForeground(new java.awt.Color(255, 255, 255));
        cbxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrigenActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        cbxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Directo" }));
        cbxModo.setBackground(new java.awt.Color(69, 130, 177));
        cbxModo.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxModo.setForeground(new java.awt.Color(255, 255, 255));
        cbxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModoActionPerformed(evt);
            }
        });

        tmPickSalida.setBackground(new java.awt.Color(69, 130, 177));
        tmPickSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        tmPickLlegada.setBackground(new java.awt.Color(69, 130, 177));
        tmPickLlegada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickLlegada.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        JTitulo.setText("Selección de Voleto");
        JTitulo.setBackground(new java.awt.Color(0, 0, 0));
        JTitulo.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 24)); // NOI18N

        btnContinuar.setBackground(new java.awt.Color(69, 130, 177));
        btnContinuar.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxModo, 0, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        
    }//GEN-LAST:event_cbxDestinoActionPerformed

    private void cbxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrigenActionPerformed
        
    }//GEN-LAST:event_cbxOrigenActionPerformed

    private void cbxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModoActionPerformed

    private void btnNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVueloActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Desea crear un nuevo vuelo?", "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                
            txtCodigo.requestFocus();
        }
        // Si elige NO, no se borra nada
    }//GEN-LAST:event_btnNuevoVueloActionPerformed

    private void txtFiltroPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroPrecioActionPerformed
        try {
            double max = Double.parseDouble(txtFiltroPrecio.getText());
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            // Aquí podrías recorrer la tabla y ocultar filas, 
        } catch(Exception e) {}
    }//GEN-LAST:event_txtFiltroPrecioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVueloActionPerformed
        
    }//GEN-LAST:event_btnEliminarVueloActionPerformed

    private void txtFiltroPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroPrecioKeyReleased
        
    }//GEN-LAST:event_txtFiltroPrecioKeyReleased

    private void tblGestionVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionVuelosMouseClicked
        int filaSeleccionada = tblGestionVuelos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigoVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 0).toString();
            String origenVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 2).toString();
            String destinoVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 3).toString();

            lblResumen.setText("Vuelo seleccionado: " + codigoVuelo + 
                    " | Trayecto: " + origenVuelo + " - " + destinoVuelo);
        }
    }//GEN-LAST:event_tblGestionVuelosMouseClicked

    private void cbxTipoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoAvionActionPerformed
        
    }//GEN-LAST:event_cbxTipoAvionActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased

    }//GEN-LAST:event_txtCodigoKeyReleased

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTitulo;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevoVuelo;
    private javax.swing.JComboBox<String> cbxDestino;
    private javax.swing.JComboBox<String> cbxModo;
    private javax.swing.JComboBox<String> cbxOrigen;
    private javax.swing.JComboBox<String> cbxTipoAvion;
    private com.github.lgooddatepicker.components.DatePicker dateRegreso;
    private com.github.lgooddatepicker.components.DatePicker dateSalida;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFechaRetorno;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTable tblGestionVuelos;
    private com.github.lgooddatepicker.components.TimePicker tmPickLlegada;
    private com.github.lgooddatepicker.components.TimePicker tmPickSalida;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFiltroPrecio;
    // End of variables declaration//GEN-END:variables

}