/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.time.LocalDate;
import javax.swing.RowFilter;
import javax.swing.RowFilter.Entry;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Avion;
import modelo.Ruta;
import modelo.Vuelo;
import control.ManejadorArchivos;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author USER
 */
public class Catalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Catalogo.class.getName());
    
    private control.ControladorBusqueda controladorBusqueda = new control.ControladorBusqueda();
    /**
     * Creates new form Catálogo
     */
    private List<modelo.Vuelo> vuelosBaseCargados = new ArrayList<>();
    
public Catalogo() {
    initComponents();
    
        // 1. Configuración del Sorter para filtrado múltiple
    DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
    
    dateSalida.getSettings().setFormatForDatesCommonEra("yyyy-MM-dd");
    dateRegreso.getSettings().setFormatForDatesCommonEra("yyyy-MM-dd");
    
    sorter.setComparator(8, (o1, o2) -> {
        // Convertimos los objetos a Double para que la tabla sepa que son dinero
        Double d1 = Double.valueOf(o1.toString());
        Double d2 = Double.valueOf(o2.toString());
        return d1.compareTo(d2);
    });

    
        tblGestionVuelos.setRowSorter(sorter);
        // 2. Cargar los 20 vuelos nacionales
        cargarDatosDesdeArchivo();

        // 3. Tus restricciones de fecha (Mantener)
        LocalDate hoy = LocalDate.now();
        dateSalida.getSettings().setDateRangeLimits(hoy, null);
        dateRegreso.getSettings().setDateRangeLimits(hoy, null);

        // 4. Tus restricciones de teclado para Precio (Mantener)
        txtFiltroPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isDigit(c) || c == '.')) {
                    evt.consume();
                }
                if (c == '.' && txtFiltroPrecio.getText().contains(".")) {
                    evt.consume();
                }
            }
        });

        // 5. Tus restricciones de teclado para Código (Mantener)
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c)) {
                    evt.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionVuelos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblResumen = new javax.swing.JLabel();
        dateSalida = new com.github.lgooddatepicker.components.DatePicker();
        jLabelFechaSalida = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        btnNuevoVuelo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminarVuelo = new javax.swing.JButton();
        cbxTipoAvion = new javax.swing.JComboBox<>();
        txtFiltroPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelFechaRetorno = new javax.swing.JLabel();
        dateRegreso = new com.github.lgooddatepicker.components.DatePicker();
        cbxDestino = new javax.swing.JComboBox<>();
        cbxOrigen = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        cbxModo = new javax.swing.JComboBox<>();
        tmPickSalida = new com.github.lgooddatepicker.components.TimePicker();
        tmPickLlegada = new com.github.lgooddatepicker.components.TimePicker();
        JTitulo = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(38, 61, 141));

        tblGestionVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Avión", "Origen", "Destino", "Fecha - Salida", "Hora - Salida", "Hora - Llegada", "Fecha - Retorno", "Precio Base", "Tipo - Equipaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGestionVuelos.setBackground(new java.awt.Color(204, 204, 204));
        tblGestionVuelos.setGridColor(new java.awt.Color(38, 61, 141));
        tblGestionVuelos.setSelectionBackground(new java.awt.Color(69, 130, 177));
        tblGestionVuelos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblGestionVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGestionVuelos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen del Vuelo Seleccionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(69, 130, 177))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        lblResumen.setBackground(new java.awt.Color(255, 255, 255));
        lblResumen.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        dateSalida.setBackground(new java.awt.Color(69, 130, 177));
        dateSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        jLabelFechaSalida.setText("Fecha - Salida");
        jLabelFechaSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelFechaSalida.setForeground(new java.awt.Color(38, 61, 141));

        jLabelDestino.setText("Destino");
        jLabelDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(38, 61, 141));

        jLabelOrigen.setText("Origen");
        jLabelOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(38, 61, 141));

        jLabel5.setText("Código");
        jLabel5.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 61, 141));

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.setBackground(new java.awt.Color(69, 130, 177));
        btnCargarDatos.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        btnNuevoVuelo.setText("Nuevo Vuelo");
        btnNuevoVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnNuevoVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnNuevoVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVueloActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBackground(new java.awt.Color(69, 130, 177));
        btnLimpiar.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminarVuelo.setText("Eliminar Vuelo");
        btnEliminarVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnEliminarVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 12)); // NOI18N
        btnEliminarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVueloActionPerformed(evt);
            }
        });

        cbxTipoAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Airbus A319", "Airbus A320neo", "Airbus A321", "Boeing 737-800", "ATR 72-600" }));
        cbxTipoAvion.setBackground(new java.awt.Color(69, 130, 177));
        cbxTipoAvion.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxTipoAvion.setForeground(new java.awt.Color(255, 255, 255));
        cbxTipoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoAvionActionPerformed(evt);
            }
        });

        txtFiltroPrecio.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        txtFiltroPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtFiltroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroPrecioActionPerformed(evt);
            }
        });
        txtFiltroPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroPrecioKeyReleased(evt);
            }
        });

        jLabel1.setText("Presupuesto");
        jLabel1.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 61, 141));

        jLabel4.setText("Avión");
        jLabel4.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 61, 141));

        jLabel2.setText("Modo");
        jLabel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 61, 141));
        jLabel2.setToolTipText("");

        jLabel6.setText("Hora - Salida");
        jLabel6.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 61, 141));

        jLabel7.setText("Hora - Llegada");
        jLabel7.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 61, 141));

        jLabelFechaRetorno.setText("Fecha - Regreso");
        jLabelFechaRetorno.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        jLabelFechaRetorno.setForeground(new java.awt.Color(38, 61, 141));

        dateRegreso.setBackground(new java.awt.Color(69, 130, 177));
        dateRegreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateRegreso.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Quito", "Guayaquil", "Cuenca" }));
        cbxDestino.setBackground(new java.awt.Color(69, 130, 177));
        cbxDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxDestino.setForeground(new java.awt.Color(255, 255, 255));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        cbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Quito", "Guayaquil", "Cuenca" }));
        cbxOrigen.setBackground(new java.awt.Color(69, 130, 177));
        cbxOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxOrigen.setForeground(new java.awt.Color(255, 255, 255));
        cbxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrigenActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        cbxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Directo" }));
        cbxModo.setBackground(new java.awt.Color(69, 130, 177));
        cbxModo.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N
        cbxModo.setForeground(new java.awt.Color(255, 255, 255));
        cbxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModoActionPerformed(evt);
            }
        });

        tmPickSalida.setBackground(new java.awt.Color(69, 130, 177));
        tmPickSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        tmPickLlegada.setBackground(new java.awt.Color(69, 130, 177));
        tmPickLlegada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickLlegada.setFont(new java.awt.Font("Open Sauce One Light", 0, 12)); // NOI18N

        JTitulo.setBackground(new java.awt.Color(0, 0, 0));
        JTitulo.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 24)); // NOI18N
        JTitulo.setText("Selección de Voleto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxModo, 0, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(96, 96, 96)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        aplicarFiltros();
        ejecutarFiltro();
    }//GEN-LAST:event_cbxDestinoActionPerformed

    private void cbxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrigenActionPerformed
        aplicarFiltros();
        ejecutarFiltro();
    }//GEN-LAST:event_cbxOrigenActionPerformed

    private void cbxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModoActionPerformed

    private void btnNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVueloActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Desea crear un nuevo vuelo?", "Confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            limpiarCampos();
            txtCodigo.requestFocus();
        }
        // Si elige NO, no se borra nada
    }//GEN-LAST:event_btnNuevoVueloActionPerformed

    private void txtFiltroPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroPrecioActionPerformed
        try {
            double max = Double.parseDouble(txtFiltroPrecio.getText());
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            // Aquí podrías recorrer la tabla y ocultar filas, 
        } catch(Exception e) {}
    }//GEN-LAST:event_txtFiltroPrecioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // 1. Limpiar TextFields
        txtCodigo.setText("");
        txtFiltroPrecio.setText("");

        // 2. Resetear ComboBoxes
        cbxTipoAvion.setSelectedIndex(0);
        cbxOrigen.setSelectedIndex(0);
        cbxDestino.setSelectedIndex(0);
        cbxModo.setSelectedIndex(0);

        // 3. LIMPIAR FECHAS Y HORAS (LGoodDatePicker)
        dateSalida.clear();
        dateRegreso.clear(); 
        tmPickSalida.clear();
        tmPickLlegada.clear(); 

        // 4. Limpiar el Label de resumen si tienes uno
        lblResumen.setText("");

        // 5. REFRESCAR LA TABLA
        aplicarFiltros(); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        if (validarCamposCompletos()) {
            try {
                // 1. Capturar datos de entrada
                String codigoIngresado = txtCodigo.getText().trim();
                String nombreAvion = cbxTipoAvion.getSelectedItem().toString();
                String origen = cbxOrigen.getSelectedItem().toString();
                String destino = cbxDestino.getSelectedItem().toString();
                String modo = cbxModo.getSelectedItem().toString();

                // 2. Validaciones de Seguridad
                if (codigoIngresado.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el código del vuelo.");
                    return;
                }

                if (!existeCodigoEnOfertas(codigoIngresado)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El código '" + codigoIngresado + "' no es una oferta válida.");
                    return;
                }

                if (cbxTipoAvion.getSelectedIndex() <= 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un tipo de avión.");
                    return;
                }

                if (!modo.equalsIgnoreCase("Directo")) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Solo operamos vuelos Directos.");
                    return;
                }

                // 3. Capturar datos técnicos (Números y Fechas)
                double precio = Double.parseDouble(txtFiltroPrecio.getText().trim());
                String fSalida = dateSalida.getDateStringOrEmptyString();
                String fRegreso = dateRegreso.getDateStringOrEmptyString();
                String hSalida = tmPickSalida.getTimeStringOrEmptyString();
                String hLlegada = tmPickLlegada.getTimeStringOrEmptyString();

                // 4. Construcción de Objetos (Composición)
                modelo.Ruta ruta = new modelo.Ruta(origen, destino);
                modelo.Avion avion = new modelo.Avion(nombreAvion);

                // Creamos el vuelo con los datos reales
                modelo.Vuelo nuevoVuelo = new modelo.Vuelo(codigoIngresado, ruta, avion,
                        fSalida, fRegreso, hSalida, hLlegada, precio);

                // 5. Guardado y Actualización
                control.ManejadorArchivos manejador = new control.ManejadorArchivos();
                manejador.guardarVuelo(nuevoVuelo);

                javax.swing.JOptionPane.showMessageDialog(this, "Vuelo registrado con éxito.");

                cargarDatosDesdeArchivo(); // Refresca la tabla automáticamente
                btnLimpiar.doClick(); // Limpia la interfaz para el siguiente vuelo

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVueloActionPerformed
        // 1. Verificar si hay una fila seleccionada
        int filaSeleccionada = tblGestionVuelos.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, seleccione un vuelo de la tabla para eliminar.",
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener el código del vuelo de la fila seleccionada (Columna 0)
        String codigo = tblGestionVuelos.getValueAt(filaSeleccionada, 0).toString();

        // 3. Confirmación
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar el vuelo " + codigo + "?",
                "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            // 4. Eliminar de la tabla visualmente
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();

            // Ajuste por si la tabla está filtrada
            int filaReal = tblGestionVuelos.convertRowIndexToModel(filaSeleccionada);
            modelo.removeRow(filaReal);

            // 5. Limpiar campos y resumen
            limpiarCampos();
            lblResumen.setText("Vuelo eliminado correctamente.");

            javax.swing.JOptionPane.showMessageDialog(this, "El vuelo ha sido retirado del catálogo.");
        }
    }//GEN-LAST:event_btnEliminarVueloActionPerformed

    private void txtFiltroPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroPrecioKeyReleased
        aplicarFiltros();
    }//GEN-LAST:event_txtFiltroPrecioKeyReleased

    private void tblGestionVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionVuelosMouseClicked
        int filaSeleccionada = tblGestionVuelos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigoVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 0).toString();
            String origenVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 2).toString();
            String destinoVuelo = tblGestionVuelos.getValueAt
                (filaSeleccionada, 3).toString();

            lblResumen.setText("Vuelo seleccionado: " + codigoVuelo + 
                    " | Trayecto: " + origenVuelo + " - " + destinoVuelo);
        }
    }//GEN-LAST:event_tblGestionVuelosMouseClicked

    private void cbxTipoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoAvionActionPerformed
        aplicarFiltros();
    }//GEN-LAST:event_cbxTipoAvionActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        aplicarFiltros();
    }//GEN-LAST:event_txtCodigoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTitulo;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevoVuelo;
    private javax.swing.JComboBox<String> cbxDestino;
    private javax.swing.JComboBox<String> cbxModo;
    private javax.swing.JComboBox<String> cbxOrigen;
    private javax.swing.JComboBox<String> cbxTipoAvion;
    private com.github.lgooddatepicker.components.DatePicker dateRegreso;
    private com.github.lgooddatepicker.components.DatePicker dateSalida;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFechaRetorno;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTable tblGestionVuelos;
    private com.github.lgooddatepicker.components.TimePicker tmPickLlegada;
    private com.github.lgooddatepicker.components.TimePicker tmPickSalida;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFiltroPrecio;
    // End of variables declaration//GEN-END:variables

    private boolean validarCamposCompletos() {
        StringBuilder faltantes = new StringBuilder();
        boolean todoOk = true;
        // Validación de Texto
        if (txtCodigo.getText().trim().isEmpty()) {
            faltantes.append("- Código del Vuelo\n");
            todoOk = false;
        }
        if (txtFiltroPrecio.getText().trim().isEmpty()) {
            faltantes.append("- Precio del Vuelo\n");
            todoOk = false;
        }

        // Validación de Fechas (JDateChooser)
        if (dateSalida.getDate() == null) {
            faltantes.append("- Fecha de Salida\n");
            todoOk = false;
        }
        if (dateRegreso.getDate() == null) {
            faltantes.append("- Fecha de Regreso\n");
            todoOk = false;
        }

        // Validación de Horas (TimePicker)
        if (tmPickSalida.getTime() == null) {
            faltantes.append("- Hora de Salida\n");
            todoOk = false;
        }

        // Si hay errores, mostramos la ventana emergente con la lista
        if (!todoOk) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Para continuar, debe llenar los siguientes campos:\n"
                            + faltantes.toString(), "Datos Faltantes",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
        }

        return todoOk;
    }
    
    private boolean existeCodigoEnOfertas(String codigo) {
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("vuelos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                // Comparamos el primer dato (Código) del archivo
                if (datos.length > 0 && datos[0].equalsIgnoreCase(codigo)) {
                    return true;
                }
            }
        } catch (java.io.IOException e) {
            System.out.println("No se pudo leer el archivo de ofertas.");
        }
        return false;
    }
    
 private void cargarDatosDesdeArchivo() {
    DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
    modelo.setRowCount(0);
    vuelosBaseCargados.clear(); // Limpiamos la "bodega" antes de volver a llenar

    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("vuelos.txt"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length >= 10) {
                // 1. CREAMOS EL OBJETO (Esto es lo que necesita tu parte de Persona 3)
                // Usamos los índices del archivo: 2=Origen, 3=Destino, 1=Avión, 0=Código, etc.
                modelo.Ruta ruta = new modelo.Ruta(datos[2], datos[3]);
                modelo.Avion avion = new modelo.Avion(datos[1]);
                modelo.Vuelo v = new modelo.Vuelo(
                    datos[0], ruta, avion, datos[4], datos[7], 
                    datos[5], datos[6], Double.parseDouble(datos[8])
                );
                
                // 2. LO GUARDAMOS en la lista global para que el buscador lo use luego
                vuelosBaseCargados.add(v);

                // 3. LO MOSTRAMOS en la tabla (Tu código original con formato)
                String horaS = formatearAMPM(datos[5]);
                String horaL = formatearAMPM(datos[6]);
                
                modelo.addRow(new Object[]{
                    datos[0], // Código
                    datos[1], // Avión
                    datos[2], // Origen
                    datos[3], // Destino
                    datos[4], // Fecha Salida
                    horaS,    // Hora Salida formateada
                    horaL,    // Hora Llegada formateada
                    datos[7], // Fecha Retorno
                    Double.parseDouble(datos[8]), // Precio
                    datos[9]  // Equipaje
                });
            }
        }
    } catch (Exception e) {
        System.out.println("Error al cargar: " + e.getMessage());
    }
}
private void actualizarTabla(List<modelo.Vuelo> filtrados) {
    DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
    modelo.setRowCount(0); // Borra todo para mostrar solo el filtro

    for (modelo.Vuelo v : filtrados) {
        modelo.addRow(new Object[]{
            v.getCodigo(),
            v.getAvion().getNombre(),
            v.getRuta().getOrigen(),
            v.getRuta().getDestino(),
            v.getFechaSalida(),
            formatearAMPM(v.getHoraSalida()), // Usamos tu método de formato
            formatearAMPM(v.getHoraLlegada()),
            v.getFechaRegreso(),
            v.getPrecioBase(),
            "Mano" // Valor por defecto
        });
    }
}
    
    private boolean validarCoincidenciaConOferta(String codigo) {
        try (java.io.BufferedReader br = new java.io.BufferedReader
            (new java.io.FileReader("vuelos.txt"))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length > 0 && datos[0].equalsIgnoreCase(codigo)) {
                    return true; // Se encontró el código en las ofertas
                }
            }
        } catch (java.io.IOException e) {
            System.out.println("Error al validar oferta: " + e.getMessage());
        }
        return false; // El código no existe en el catálogo
    }
    
    private String formatearAMPM(String hora24) {
        try {
            // De "15:00" a "03:00 PM"
            java.time.LocalTime tiempo = java.time.LocalTime.parse(hora24);
            return tiempo.format(java.time.format.DateTimeFormatter.ofPattern("hh:mm a"));
        } catch (Exception e) {
            return hora24; // Retorna original si hay error
        }
    }

    private void aplicarFiltros() {
        TableRowSorter<DefaultTableModel> sorter = (TableRowSorter<DefaultTableModel>)
                tblGestionVuelos.getRowSorter();
        if (sorter == null) {
            return;
        }

        List<RowFilter<Object, Object>> filtros = new ArrayList<>();
        // 1. Código (Columna 0)
        if (!txtCodigo.getText().trim().isEmpty()) {
            // (?i) hace que "v001" encuentre a "V001"
            filtros.add(RowFilter.regexFilter("(?i)" + txtCodigo.getText().trim(), 0));
        }

        // 2. Avión (Columna 1) - Basado en tu ComboBox cbxTipoAvion
        if (cbxTipoAvion.getSelectedIndex() > 0) {
            filtros.add(RowFilter.regexFilter(cbxTipoAvion.getSelectedItem().toString(), 1));
        }

        // 3. Origen y 4. Destino (Columnas 2 y 3)
        if (cbxOrigen.getSelectedIndex() > 0) {
            filtros.add(RowFilter.regexFilter(cbxOrigen.getSelectedItem().toString(), 2));
        }
        if (cbxDestino.getSelectedIndex() > 0) {
            filtros.add(RowFilter.regexFilter(cbxDestino.getSelectedItem().toString(), 3));
        }

        // 5. Presupuesto (Columna 8)
        String pres = txtFiltroPrecio.getText().trim();
        if (!pres.isEmpty()) {
            try {
                double limite = Double.parseDouble(pres);
                // Columna 8: Precio
                filtros.add(RowFilter.numberFilter(RowFilter.ComparisonType.BEFORE, limite, 8));
            } catch (NumberFormatException e) {
            }
        }

        // 6. Filtro por Fechas (Columna 4) - CORRECCIÓN PARA DATEPICKER
        if (dateSalida.getDate() != null) {
            // Usamos el método propio del DatePicker para obtener el texto
            String fechaS = dateSalida.getDateStringOrEmptyString();
            filtros.add(RowFilter.regexFilter(fechaS, 4));
        }

        // 7. Filtro por Horas (Columna 5) - CORRECCIÓN PARA TIMEPICKER
        if (tmPickSalida.getTime() != null) {
            String horaS = tmPickSalida.getTimeStringOrEmptyString();
            filtros.add(RowFilter.regexFilter(horaS, 5));
        }

        // Aplicar filtros combinados
        if (filtros.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.andFilter(filtros));
        }
    }
    
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtFiltroPrecio.setText("");
        dateSalida.clear();
        dateRegreso.clear();
        tmPickSalida.clear(); 
        tmPickLlegada.clear();
        cbxOrigen.setSelectedIndex(0);
        cbxDestino.setSelectedIndex(0);
    }
private void ejecutarFiltro() {
    // 1. Obtener valores de la interfaz
    String origen = cbxOrigen.getSelectedItem().toString();
    String destino = cbxDestino.getSelectedItem().toString();
    
    // 2. Manejar el presupuesto (si está vacío, usamos un número muy grande)
    double presupuesto = 999999.0; 
    try {
        String textoPrecio = txtFiltroPrecio.getText().trim();
        if (!textoPrecio.isEmpty()) {
            presupuesto = Double.parseDouble(textoPrecio);
        }
    } catch (NumberFormatException e) {
        // Si escriben letras, no filtramos por precio
    }

    // 3. LÓGICA DINÁMICA: Si el usuario no ha elegido ciudades, mostramos todo
    if (origen.equals("-----------") || destino.equals("-----------")) {
        actualizarTabla(vuelosBaseCargados); 
    } else {
        // 4. Si hay ciudades, usamos TU Controlador (Persona 3)
        List<modelo.Vuelo> filtrados = controladorBusqueda.buscar(vuelosBaseCargados, origen, destino, presupuesto);
        actualizarTabla(filtrados);
    }
}
}
