/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.time.LocalDate;
import javax.swing.RowFilter;
import javax.swing.RowFilter.Entry;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Avion;
import modelo.Ruta;
import modelo.Vuelo;

/**
 *
 * @author USER
 */
public class Catalogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Catalogo.class.getName());

    /**
     * Creates new form Catálogo
     */
    public Catalogo() {
        initComponents();
        
    LocalDate hoy = LocalDate.now();
    dateSalida.getSettings().setDateRangeLimits(hoy, null);
    dateRegreso.getSettings().setDateRangeLimits(hoy, null);
        
            // Restricción para el Precio: Solo números positivos y un punto decimal
    txtFiltroPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!(Character.isDigit(c) || c == '.')) {
                evt.consume(); // Bloquea cualquier cosa que no sea número o punto
            }
            if (c == '.' && txtFiltroPrecio.getText().contains(".")) {
                evt.consume(); // Bloquea si ya existe un punto
            }
        }
    });

    // Restricción para el Código: Solo letras y números (sin espacios)
    txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isLetterOrDigit(c)) {
                evt.consume();
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestionVuelos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblResumen = new javax.swing.JLabel();
        dateSalida = new com.github.lgooddatepicker.components.DatePicker();
        jLabelFechaSalida = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCargarDatos = new javax.swing.JButton();
        btnNuevoVuelo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnEliminarVuelo = new javax.swing.JButton();
        cbxTipoAvion = new javax.swing.JComboBox<>();
        txtFiltroPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelFechaRetorno = new javax.swing.JLabel();
        dateRegreso = new com.github.lgooddatepicker.components.DatePicker();
        cbxDestino = new javax.swing.JComboBox<>();
        cbxOrigen = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        cbxModo = new javax.swing.JComboBox<>();
        tmPickSalida = new com.github.lgooddatepicker.components.TimePicker();
        tmPickLlegada = new com.github.lgooddatepicker.components.TimePicker();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tblGestionVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Avión", "Origen", "Destino", "Fecha - Salida", "Hora - Salida", "Hora - Llegada", "Fecha - Retorno", "Precio Base", "Tipo - Equipaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGestionVuelos.setForeground(new java.awt.Color(255, 255, 255));
        tblGestionVuelos.setGridColor(new java.awt.Color(255, 153, 102));
        tblGestionVuelos.setSelectionBackground(new java.awt.Color(69, 130, 177));
        tblGestionVuelos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblGestionVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGestionVuelos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen del Vuelo Seleccionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(69, 130, 177))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        lblResumen.setBackground(new java.awt.Color(255, 255, 255));
        lblResumen.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        dateSalida.setBackground(new java.awt.Color(69, 130, 177));
        dateSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabelFechaSalida.setText("Fecha - Salida");
        jLabelFechaSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabelDestino.setText("Destino");
        jLabelDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabelOrigen.setText("Origen");
        jLabelOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabel5.setText("Código");
        jLabel5.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.setBackground(new java.awt.Color(69, 130, 177));
        btnCargarDatos.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        btnCargarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        btnNuevoVuelo.setText("Nuevo Vuelo");
        btnNuevoVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnNuevoVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        btnNuevoVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVueloActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.setBackground(new java.awt.Color(69, 130, 177));
        jButton1.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminarVuelo.setText("Eliminar Vuelo");
        btnEliminarVuelo.setBackground(new java.awt.Color(69, 130, 177));
        btnEliminarVuelo.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        btnEliminarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVueloActionPerformed(evt);
            }
        });

        cbxTipoAvion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airbus A319", "Airbus A320neo", "Airbus A321", "Boeing 737-800", "ATR 72-600" }));
        cbxTipoAvion.setBackground(new java.awt.Color(69, 130, 177));
        cbxTipoAvion.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        cbxTipoAvion.setForeground(new java.awt.Color(255, 255, 255));

        txtFiltroPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtFiltroPrecio.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        txtFiltroPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroPrecioActionPerformed(evt);
            }
        });
        txtFiltroPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroPrecioKeyReleased(evt);
            }
        });

        jLabel1.setText("Presupuesto");
        jLabel1.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabel4.setText("Avión");
        jLabel4.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabel2.setText("Modo");
        jLabel2.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        jLabel2.setToolTipText("");

        jLabel6.setText("Hora - Salida");
        jLabel6.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabel7.setText("Hora - Llegada");
        jLabel7.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        jLabelFechaRetorno.setText("Fecha - Regreso");
        jLabelFechaRetorno.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        dateRegreso.setBackground(new java.awt.Color(69, 130, 177));
        dateRegreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        dateRegreso.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        cbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "Guayaquil", "Cuenca" }));
        cbxDestino.setBackground(new java.awt.Color(69, 130, 177));
        cbxDestino.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        cbxDestino.setForeground(new java.awt.Color(255, 255, 255));
        cbxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDestinoActionPerformed(evt);
            }
        });

        cbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "Guayaquil", "Cuenca" }));
        cbxOrigen.setBackground(new java.awt.Color(69, 130, 177));
        cbxOrigen.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        cbxOrigen.setForeground(new java.awt.Color(255, 255, 255));
        cbxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOrigenActionPerformed(evt);
            }
        });

        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        txtCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigo.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        cbxModo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Directo" }));
        cbxModo.setBackground(new java.awt.Color(69, 130, 177));
        cbxModo.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N
        cbxModo.setForeground(new java.awt.Color(255, 255, 255));
        cbxModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxModoActionPerformed(evt);
            }
        });

        tmPickSalida.setBackground(new java.awt.Color(69, 130, 177));
        tmPickSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickSalida.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        tmPickLlegada.setBackground(new java.awt.Color(69, 130, 177));
        tmPickLlegada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 130, 177)));
        tmPickLlegada.setFont(new java.awt.Font("Open Sauce One Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(286, 286, 286))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxModo, 0, 125, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxModo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltroPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tmPickLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDestinoActionPerformed

    private void cbxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxOrigenActionPerformed

    private void cbxModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxModoActionPerformed

    private void btnNuevoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVueloActionPerformed
        try {
            // 1. Validar Código
            if (txtCodigo.getText().trim().isEmpty()) {
                txtCodigo.requestFocus(); // El cursor salta aquí
                throw new Exception("Falta ingresar el CÓDIGO del vuelo.");
            }

            // 2. Validar Precio
            if (txtFiltroPrecio.getText().trim().isEmpty()) {
                txtFiltroPrecio.requestFocus(); // El cursor salta aquí
                throw new Exception("Falta ingresar el PRECIO del vuelo.");
            }

            // 3. Validar Fechas (Como son DatePickers, no usamos requestFocus, solo el aviso)
            if (dateSalida.getDate() == null) {
                throw new Exception("Falta seleccionar la FECHA DE SALIDA.");
            }
            if (dateRegreso.getDate() == null) {
                throw new Exception("Falta seleccionar la FECHA DE REGRESO.");
            }

            // 4. Validar Horas
            if (tmPickSalida.getTime() == null) {
                throw new Exception("Falta seleccionar la HORA DE SALIDA.");
            }
            if (tmPickLlegada.getTime() == null) {
                throw new Exception("Falta seleccionar la HORA DE LLEGADA.");
            }

            // 2. Validar que Origen y Destino no sean iguales
            String origen = cbxOrigen.getSelectedItem().toString();
            String destino = cbxDestino.getSelectedItem().toString();
            if (origen.equals(destino)) {
                throw new Exception("El origen y el destino no pueden ser el mismo.");
            }

            // 3. Validar Rango de Fechas (Regreso no puede ser antes que Salida)
            if (dateRegreso.getDate().isBefore(dateSalida.getDate())) {
                throw new Exception("La fecha de regreso debe ser posterior "
                        + "o igual a la de salida.");
            }

            // 4. Crear los objetos (Composición)
            Ruta ruta = new Ruta(origen, destino);
            Avion avion = new Avion(cbxTipoAvion.getSelectedItem().toString());
            Vuelo vuelo = new Vuelo(
                    txtCodigo.getText(), ruta, avion,
                    dateSalida.getDateStringOrEmptyString(),
                    dateRegreso.getDateStringOrEmptyString(),
                    tmPickSalida.getTimeStringOrEmptyString(),
                    tmPickLlegada.getTimeStringOrEmptyString(),
                    Double.parseDouble(txtFiltroPrecio.getText())
            );

            // 5. Agregar a la Tabla
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            modelo.addRow(new Object[]{
                vuelo.getCodigo(), avion.getNombre(), origen, destino,
                vuelo.getHoraSalida(), vuelo.getHoraLlegada(),
                vuelo.getFechaSalida(), vuelo.getFechaRegreso(),
                vuelo.getPrecioBase()
            });

            // 6. Guardar en el archivo .txt
            guardarEnArchivo(vuelo);
            lblResumen.setText("Vuelo " + vuelo.getCodigo()
                    + " registrado y guardado.");
            limpiarCampos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Error de Registro", 0);
        }
    }

    // Método para guardar en el archivo de texto
    private void guardarEnArchivo(Vuelo v) {
        try (java.io.FileWriter fw = new java.io.FileWriter("vuelos.txt", true); java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {
            pw.println(v.toString()); // Usamos el toString que creamos en la clase Vuelo
        } catch (Exception e) {
            // El mensaje ahora mostrará exactamente qué Exception se disparó arriba
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Campo Requerido", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoVueloActionPerformed

    private void txtFiltroPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroPrecioActionPerformed
        try {
            double max = Double.parseDouble(txtFiltroPrecio.getText());
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            // Aquí podrías recorrer la tabla y ocultar filas, 
        } catch(Exception e) {}
    }//GEN-LAST:event_txtFiltroPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCampos();
        lblResumen.setText("Formulario reiniciado.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        control.ManejadorArchivos manejador = new control.ManejadorArchivos();
        java.util.ArrayList<modelo.Vuelo> lista = manejador.cargarVuelos();

        try {
            // Llamamos a tu método de carga
            cargarDatosDesdeArchivo();

            // Contamos cuántas filas hay ahora en la tabla
            int totalVuelos = tblGestionVuelos.getRowCount();

            if (totalVuelos > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Se han cargado " + totalVuelos + " vuelos exitosamente desde el archivo.",
                        "Carga Exitosa",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El archivo está vacío o no existen vuelos registrados.",
                        "Aviso",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnEliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVueloActionPerformed
    int fila = tblGestionVuelos.getSelectedRow();
        if (fila != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            modelo.removeRow(fila);
            lblResumen.setText("Vuelo eliminado del catálogo.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un vuelo de la tabla.");
        }
    }//GEN-LAST:event_btnEliminarVueloActionPerformed

    private void txtFiltroPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroPrecioKeyReleased
        TableRowSorter<TableModel> ordenador = new TableRowSorter<>(tblGestionVuelos.getModel());
        tblGestionVuelos.setRowSorter(ordenador);
        
        String filtro = txtFiltroPrecio.getText();
        if (filtro.isEmpty()) {
            ordenador.setRowFilter(null);
        } else {
            try {
                double precioMaximo = Double.parseDouble(filtro);
                // Filtra la columna 8 (Precio Base) para mostrar solo lo menor o igual
                ordenador.setRowFilter(new RowFilter<TableModel, Integer>() {
                    @Override
                    public boolean include(Entry<? extends TableModel, ? extends Integer> entry) {
                        double precioFila = Double.parseDouble(entry.getStringValue(8));
                        return precioFila <= precioMaximo;
                    }
                });
            } catch (NumberFormatException e) {
                // Si el usuario escribe letras en el precio, no hacemos nada
            }
        }
    }//GEN-LAST:event_txtFiltroPrecioKeyReleased

    private void tblGestionVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionVuelosMouseClicked
        int filaSeleccionada = tblGestionVuelos.getSelectedRow();
        if (filaSeleccionada != -1) {
            String codigoVuelo = tblGestionVuelos.getValueAt(filaSeleccionada, 0).toString();
            String origenVuelo = tblGestionVuelos.getValueAt(filaSeleccionada, 2).toString();
            String destinoVuelo = tblGestionVuelos.getValueAt(filaSeleccionada, 3).toString();

            lblResumen.setText("Vuelo seleccionado: " + codigoVuelo + " | Trayecto: " + origenVuelo + " - " + destinoVuelo);
        }
    }//GEN-LAST:event_tblGestionVuelosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEliminarVuelo;
    private javax.swing.JButton btnNuevoVuelo;
    private javax.swing.JComboBox<String> cbxDestino;
    private javax.swing.JComboBox<String> cbxModo;
    private javax.swing.JComboBox<String> cbxOrigen;
    private javax.swing.JComboBox<String> cbxTipoAvion;
    private com.github.lgooddatepicker.components.DatePicker dateRegreso;
    private com.github.lgooddatepicker.components.DatePicker dateSalida;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFechaRetorno;
    private javax.swing.JLabel jLabelFechaSalida;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JTable tblGestionVuelos;
    private com.github.lgooddatepicker.components.TimePicker tmPickLlegada;
    private com.github.lgooddatepicker.components.TimePicker tmPickSalida;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFiltroPrecio;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosIniciales() {
        try {
            control.ManejadorArchivos manejador = new control.ManejadorArchivos();
            java.util.ArrayList<modelo.Vuelo> lista = manejador.cargarVuelos();

            DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
            // Limpiamos la tabla por si acaso
            modelo.setRowCount(0); 

            for (modelo.Vuelo vuelo : lista) {
                modelo.addRow(new Object[]{
                    vuelo.getCodigo(), vuelo.getAvion().getNombre(),
                    vuelo.getRuta().getOrigen(), vuelo.getRuta().getDestino(),
                    vuelo.getHoraSalida(), vuelo.getHoraLlegada(),
                    vuelo.getFechaSalida(), vuelo.getFechaRegreso(),
                    vuelo.getPrecioBase()
                });
            }
        } catch (Exception e) {
            System.out.println("Aún no hay datos para cargar o error en ruta.");
        }
    }
    
    private void cargarDatosDesdeArchivo() {
    DefaultTableModel modelo = (DefaultTableModel) tblGestionVuelos.getModel();
    modelo.setRowCount(0); // Limpia la tabla antes de cargar
    
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("vuelos.txt"))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(",");
            // El orden debe coincidir con tu método toString() de la clase Vuelo
            modelo.addRow(new Object[]{
                datos[0], // Código
                datos[8], // Avión
                datos[1], // Origen
                datos[2], // Destino
                datos[5], // Hora Salida
                datos[6], // Hora Llegada
                datos[3], // Fecha Salida
                datos[4], // Fecha Regreso
                datos[7]  // Precio Base
            });
        }
    } catch (java.io.IOException e) {
        System.out.println("Archivo no encontrado. Se creará uno nuevo al guardar un vuelo.");
    }
}
    
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtFiltroPrecio.setText(""); // Asegúrate que el nombre coincida con tu campo de precio
        dateSalida.clear();
        dateRegreso.clear();
        tmPickSalida.clear(); // Revisa si así llamaste a tus TimePickers
        tmPickLlegada.clear();
        cbxOrigen.setSelectedIndex(0);
        cbxDestino.setSelectedIndex(0);
    }
    
}
