/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author USUARIO
 */
public class VentanaRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistro.class.getName());

    private java.util.List<control.ControladorPasajero> listaControladores = new java.util.ArrayList<>();
    
private int cantAdultos;
private int cantNinos;
private int cantBebes;

// CONSTRUCTOR NUEVO: Recibe las cantidades
public VentanaRegistro(int adultos, int ninos, int bebes) {
    initComponents();
    this.cantAdultos = adultos;
    this.cantNinos = ninos;
    this.cantBebes = bebes;
    
    // 1. Limpieza inicial
    tabsPasajeros.removeAll(); 
    listaControladores.clear(); 

    // Bucle para crear tantas pestañas de ADULTO, niños y bebes como se pidieron
    for (int i = 1; i <= adultos; i++) {
        agregarPestaña("ADULTO", i);
    }

    for (int i = 1; i <= ninos; i++) {
        agregarPestaña("NIÑO", i);
    }

    for (int i = 1; i <= bebes; i++) {
        agregarPestaña("BEBÉ", i);
    }
}

// Método auxiliar para no repetir código (DRY)
private void agregarPestaña(String tipo, int numero) {
    control.ControladorPasajero ctrl = new control.ControladorPasajero();
    ctrl.configurarTipo(tipo, numero);
    
    // Guardamos en la lista
    listaControladores.add(ctrl);
    
    // Agregamos al TabbedPane con título bonito (Ej: "Adulto 1")
    // Truco: Capitalizamos la primera letra (Adulto 1) para que se vea bien
    String titulo = tipo.charAt(0) + tipo.substring(1).toLowerCase() + " " + numero;
    tabsPasajeros.addTab(titulo, ctrl.getVista());
    
    
    
}


    public javax.swing.JButton getBtnContinuar() {
        return btnContinuar;
   
}

    // --- PEGAR ESTO ANTES DE LA ÚLTIMA LLAVE } EN VentanaRegistro.java ---

    public java.util.List<modelo.Pasajero> obtenerPasajerosIngresados() throws Exception {
        java.util.List<modelo.Pasajero> lista = new java.util.ArrayList<>();
        
        // Recorremos cada pestañita que creamos
        for (control.ControladorPasajero ctrl : listaControladores) {
            try {
                // Intentamos sacar los datos (esto valida si están vacíos)
                modelo.Pasajero p = ctrl.obtenerDatosControlados();
                lista.add(p);
            } catch (Exception e) {
                // Si hay error (campo vacío), enfocamos esa pestaña automáticamente
                tabsPasajeros.setSelectedComponent(ctrl.getVista());
                throw e; // Lanzamos el error para que el Controlador muestre el mensaje
            }
        }
        return lista;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabsPasajeros = new javax.swing.JTabbedPane();
        btnContinuar = new javax.swing.JButton();
        JTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(167, 208, 210));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabsPasajeros.setBackground(new java.awt.Color(167, 208, 210));
        tabsPasajeros.setForeground(new java.awt.Color(167, 208, 210));
        tabsPasajeros.setToolTipText("");
        tabsPasajeros.setFont(new java.awt.Font("Open Sauce Sans ExtraBold", 0, 14)); // NOI18N

        btnContinuar.setFont(new java.awt.Font("Open Sauce One SemiBold", 0, 14)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuar)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tabsPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JTitulo.setBackground(new java.awt.Color(0, 0, 0));
        JTitulo.setFont(new java.awt.Font("Open Sauce One ExtraBold", 0, 36)); // NOI18N
        JTitulo.setText("Registro de Pasajeros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
                                           
    java.util.List<modelo.Pasajero> pasajerosListos = new java.util.ArrayList<>();

    // 1. VALIDACIÓN
    for (control.ControladorPasajero ctrl : listaControladores) {
        try {
           modelo.Pasajero p = ctrl.obtenerDatosControlados();
           pasajerosListos.add(p);
        } catch (Exception e) {
            tabsPasajeros.setSelectedComponent(ctrl.getVista()); // Ir a la pestaña del error
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }
    }
   
    // 2. GUARDAR EN TXT
    try {
        servicios.GestorArchivos.guardarDatos(pasajerosListos, "RegistroPasajeros.txt");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Registro Exitoso! Archivo creado.");
        

        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar archivo: " + e.getMessage());
    }
    
    // ... (aquí están tus variables declaration como private javax.swing.JButton btnContinuar; etc) ..
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRegistro(1,0,1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTitulo;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabsPasajeros;
    // End of variables declaration//GEN-END:variables
}
